services:
  app:
    image: openclue.fsharptodo
    build:
      context: .
      dockerfile: src/OpenClue.FSharpToDo/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__Marten=Host=db;Database=todo;Username=postgres;Password=Gh5634!X
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Gh5634!X
      POSTGRES_DB: todo
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  
volumes:
  db-data:
